version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ghcr.io/alphakartik/dockerized-ci-cd-app-backend:latest
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ghcr.io/alphakartik/dockerized-ci-cd-app-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
